import { relative, resolve } from 'node:path';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { DEFAULT_CONFIG } from '../constants.js';

export interface GeneratedEntryPaths {
	readonly client: string;
	readonly server: string;
	readonly generated: boolean;
}

/** Runtimes for which a standalone listening server entry can be generated. */
export type ServerRuntime = 'node' | 'bun';

const ADAPTER_IMPORT: Record<
	ServerRuntime,
	{ factory: string; module: string }
> = {
	node: { factory: 'createNodeServer', module: '@effuse/server/node' },
	bun: { factory: 'createBunServer', module: '@effuse/server/bun' },
};

/**
 * Renders a standalone server entry that binds the shared `@effuse/server`
 * adapter to the SSR `handleRequest` and wires graceful shutdown. `handlerImport`
 * is the module specifier (relative to `.effuse/`) that exports `handleRequest`.
 */
const renderServerBootstrap = (
	runtime: ServerRuntime,
	handlerImport: string
): string => {
	const { factory, module } = ADAPTER_IMPORT[runtime];
	const label = runtime === 'bun' ? 'Bun' : 'Node';

	return `// Auto-generated by @effuse/cli — ${label} production server entry.
// This file is recreated on every build. It binds the shared @effuse/server
// adapter to the SSR handler and listens on the configured host/port.

import { ${factory}, withStaticFiles } from '${module}';
import { handleRequest } from '${handlerImport}';

const port = Number(process.env.PORT ?? 3000);
const host = process.env.HOST ?? '0.0.0.0';

const clientRoot = new URL('../client/', import.meta.url);
const server = ${factory}(withStaticFiles(handleRequest, { root: clientRoot }));

const address = await server.listen({ port, host });
console.log(\`[effuse] ${label} server listening on \${address.url}\`);

const shutdown = (signal: string): void => {
	console.log(\`\\n[effuse] \${signal} received, draining connections…\`);
	server
		.close()
		.then(() => process.exit(0))
		.catch((error: unknown) => {
			console.error('[effuse] Shutdown failed:', error);
			process.exit(1);
		});
};

process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));
`;
};

const CLIENT_ENTRY_TEMPLATE = `// Auto-generated by @effuse/cli
// This file is recreated on every dev/build start.
// To use a custom entry, create src/entry-client.ts

import { app } from '../src/app.ts';
import '@effuse/core/hmr/global';

async function bootstrap() {
	await app.mount('#app');
}

bootstrap().catch((err) => {
	console.error('[effuse] Client bootstrap failed:', err);
});
`;

const SERVER_ENTRY_TEMPLATE = `// Auto-generated by @effuse/cli
// This file is recreated on every dev/build start.
// To use a custom entry, create src/entry-server.ts

import { app } from '../src/app.ts';
import type { AssetManifest } from '@effuse/core';

let manifest: AssetManifest | undefined;

try {
	manifest = JSON.parse(
		await (await import('node:fs')).promises.readFile(
			new URL('./manifest.json', import.meta.url),
			'utf-8'
		)
	);
} catch {
	// No manifest available — dev mode or client-only build
}

export async function handleRequest(request: Request): Promise<Response> {
	try {
		return app.handleRequest(request, manifest ? { manifest } : {});
	} catch (error) {
		console.error('[effuse] SSR render error:', error);
		return new Response(
			'<!DOCTYPE html><html><body><h1>500 Internal Server Error</h1></body></html>',
			{ status: 500, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
		);
	}
}
`;

export class EntryGenerator {
	generate(cwd: string): GeneratedEntryPaths {
		const userClientEntry = resolve(cwd, DEFAULT_CONFIG.entryClient);
		const userServerEntry = resolve(cwd, DEFAULT_CONFIG.entryServer);
		const generatedDir = resolve(cwd, '.effuse');

		const hasUserClient = existsSync(userClientEntry);
		const hasUserServer = existsSync(userServerEntry);
		const hasAppFile = existsSync(resolve(cwd, 'src/app.ts'));

		// If user has custom entries, use them
		if (hasUserClient && hasUserServer) {
			return {
				client: DEFAULT_CONFIG.entryClient,
				server: DEFAULT_CONFIG.entryServer,
				generated: false,
			};
		}

		// If no app.ts exists, we can't auto-generate
		if (!hasAppFile) {
			return {
				client: DEFAULT_CONFIG.entryClient,
				server: DEFAULT_CONFIG.entryServer,
				generated: false,
			};
		}

		// Create .effuse directory if needed
		if (!existsSync(generatedDir)) {
			mkdirSync(generatedDir, { recursive: true });
		}

		const generatedClient = resolve(generatedDir, 'entry-client.ts');
		const generatedServer = resolve(generatedDir, 'entry-server.ts');

		if (!hasUserClient) {
			writeFileSync(generatedClient, CLIENT_ENTRY_TEMPLATE, 'utf-8');
		}

		if (!hasUserServer) {
			writeFileSync(generatedServer, SERVER_ENTRY_TEMPLATE, 'utf-8');
		}

		return {
			client: hasUserClient
				? DEFAULT_CONFIG.entryClient
				: '.effuse/entry-client.ts',
			server: hasUserServer
				? DEFAULT_CONFIG.entryServer
				: '.effuse/entry-server.ts',
			generated: true,
		};
	}

	/**
	 * Writes a standalone listening server entry for `runtime` into `.effuse/`
	 * and returns its path relative to `cwd` (for use as a build input). The
	 * generated entry imports `handleRequest` from `serverEntry` (the path
	 * returned by {@link generate}) via a relative specifier.
	 */
	generateServerBootstrap(
		cwd: string,
		serverEntry: string,
		runtime: ServerRuntime
	): string {
		const generatedDir = resolve(cwd, '.effuse');
		if (!existsSync(generatedDir)) {
			mkdirSync(generatedDir, { recursive: true });
		}

		const rawImport = relative(generatedDir, resolve(cwd, serverEntry)).replace(
			/\\/g,
			'/'
		);
		const handlerImport = rawImport.startsWith('.')
			? rawImport
			: `./${rawImport}`;

		const bootstrapRelative = `.effuse/entry-${runtime}.ts`;
		writeFileSync(
			resolve(cwd, bootstrapRelative),
			renderServerBootstrap(runtime, handlerImport),
			'utf-8'
		);

		return bootstrapRelative;
	}
}
