import { resolve } from 'node:path';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { DEFAULT_CONFIG } from '../constants.js';

export interface GeneratedEntryPaths {
	readonly client: string;
	readonly server: string;
	readonly generated: boolean;
}

const CLIENT_ENTRY_TEMPLATE = `// Auto-generated by @effuse/cli
// This file is recreated on every dev/build start.
// To use a custom entry, create src/entry-client.ts

import { app } from '../src/app.ts';

async function bootstrap() {
	await app.mount('#app');
}

bootstrap().catch((err) => {
	console.error('[effuse] Client bootstrap failed:', err);
});
`;

const SERVER_ENTRY_TEMPLATE = `// Auto-generated by @effuse/cli
// This file is recreated on every dev/build start.
// To use a custom entry, create src/entry-server.ts

import { app } from '../src/app.ts';

let manifest: Record<string, unknown> | undefined;

try {
	manifest = JSON.parse(
		await (await import('node:fs')).promises.readFile(
			new URL('./manifest.json', import.meta.url),
			'utf-8'
		)
	);
} catch {
	// No manifest available — dev mode or client-only build
}

export async function handleRequest(request: Request): Promise<Response> {
	try {
		const url = new URL(request.url);
		const serverApp = app.getServerApp();
		if (manifest) {
			serverApp.configure({ manifest });
		}
		const stream = await serverApp.renderToStream(url.pathname);
		return new Response(stream, {
			status: 200,
			headers: {
				'Content-Type': 'text/html; charset=utf-8',
			},
		});
	} catch (error) {
		console.error('[effuse] SSR render error:', error);
		return new Response(
			'<!DOCTYPE html><html><body><h1>500 Internal Server Error</h1></body></html>',
			{ status: 500, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
		);
	}
}
`;

export class EntryGenerator {
	generate(cwd: string): GeneratedEntryPaths {
		const userClientEntry = resolve(cwd, DEFAULT_CONFIG.entryClient);
		const userServerEntry = resolve(cwd, DEFAULT_CONFIG.entryServer);
		const generatedDir = resolve(cwd, '.effuse');

		const hasUserClient = existsSync(userClientEntry);
		const hasUserServer = existsSync(userServerEntry);
		const hasAppFile = existsSync(resolve(cwd, 'src/app.ts'));

		// If user has custom entries, use them
		if (hasUserClient && hasUserServer) {
			return {
				client: DEFAULT_CONFIG.entryClient,
				server: DEFAULT_CONFIG.entryServer,
				generated: false,
			};
		}

		// If no app.ts exists, we can't auto-generate
		if (!hasAppFile) {
			return {
				client: DEFAULT_CONFIG.entryClient,
				server: DEFAULT_CONFIG.entryServer,
				generated: false,
			};
		}

		// Create .effuse directory if needed
		if (!existsSync(generatedDir)) {
			mkdirSync(generatedDir, { recursive: true });
		}

		const generatedClient = resolve(generatedDir, 'entry-client.ts');
		const generatedServer = resolve(generatedDir, 'entry-server.ts');

		if (!hasUserClient) {
			writeFileSync(generatedClient, CLIENT_ENTRY_TEMPLATE, 'utf-8');
		}

		if (!hasUserServer) {
			writeFileSync(generatedServer, SERVER_ENTRY_TEMPLATE, 'utf-8');
		}

		return {
			client: hasUserClient ? DEFAULT_CONFIG.entryClient : '.effuse/entry-client.ts',
			server: hasUserServer ? DEFAULT_CONFIG.entryServer : '.effuse/entry-server.ts',
			generated: true,
		};
	}
}
